#!/bin/sh
#
# @name AMOVLAB P450
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MC_PITCHRATE_P 0.1
param set-default MC_ROLLRATE_P 0.1
param set-default MC_ROLLRATE_D 0.0017
param set-default MC_ROLLRATE_P 0.076
param set-default MC_ROLLRATE_I 0.187
param set-default MC_ROLL_P 6.86

set MIXER quad_x
